var data  = {
 "Maison Rostang": "Maison Rostang",
 "Restaurant Pierre Orsi": "Pierre",
 "Lucas Carton": "Lucas Carton",
 "Château de Berne (Var)": "Le Jardin de Benjamin",
 "Maison Doucet (Saône et Loire)": "Frédéric Doucet",
 "Hôtel et Restaurant Régis et Jacques Marcon (Haute-Loire)": "Régis et Jacques Marcon",
 "Auberge du Jeu de Paume (Oise)": "La Table du Connétable",
 "Hôtel Restaurant Clos des Sens - Laurent PETIT (Haute-Savoie)": "Laurent",
 "Le Phébus & Spa - Villa des Anges (Vaucluse)": "Xavier Mathieu",
 "Michel Trama (Lot-et-Garonne)": "Michel Trama",
 "Au Cœur du Village Hôtel & Spa (Rhône-Alpes)": "Le Cinq",
 "Le Petit Nice-Passedat (Bouches-du-Rhône)": "Le Petit Nice",
 "Monte-Carlo Beach (Alpes-Maritimes)": "Elsa",
 "La Côte Saint Jacques & Spa (Yonne)": "La Côte Saint-Jacques",
 "Yoann Conte – Bord du Lac Hôtel Restaurant (Haute-Savoie)": "Côté Jardin",
 "Maison Pic (Drôme)": "Pic",
 "Restaurant Serge Vieira (Cantal)": "Serge Vieira",
 "Le Saint-James Bouliac (Gironde)": "Le Saint-James",
 "Cap d’Antibes Beach Hotel (Alpes-Maritimes)": "Les Pêcheurs",
 "L’Oasis": "L'Oasis",
 "Baumanière Hôtel & Spa (Bouches-du-Rhône)": "L'Oustau de Baumanière",
 "Maison Lameloise (Saône-et-Loire)": "Maison Lameloise",
 "Relais de la Poste (Landes)": "Relais de la Poste",
 "Château de La Chèvre d’Or (Alpes-Maritimes)": "La Chèvre d'Or",
 "Hôtel Les Barmes de l'Ours (Savoie)": "La Table de l'Ours",
 "La Bonne Étape (Alpes-de-Haute-Provence)": "La Bonne Étape",
 "Royal Champagne Hotel & Spa (Marne)": "Le Royal",
 "La Grenouillère (Pas-de-Calais)": "La Grenouillère",
 "Hôtel Crillon le Brave (Vaucluse)": "La Madeleine",
 "Le Vieux Logis (Dordogne)": "Le Vieux Logis",
 "Hôtel Le Chabichou Restaurants & Spa (Savoie)": "Le Chabichou",
 "Le Chambard (Haut-Rhin)": "La Table d'Olivier Nasti",
 "Hôtel Restaurant Auberge du Père Bise – Jean Sulpice (Haute-Savoie)": "Pic",
 "Hôtel Impérial Garoupe (Alpes-Maritimes)": "Le Pavillon",
 "Flocons de Sel (Haute-Savoie)": "Flocons de Sel",
 "Château de Valmer (Var)": "La Palmeraie",
 "Georges Blanc Parc & Spa (Ain)": "Georges Blanc",
 "Hameau Albert Ier (Haute-Savoie)": "Albert 1er",
 "Domaine Les Crayères (Marne)": "Bras",
 "Le Couvent des Minimes Hôtel & Spa L'Occitane (Alpes-de-Haute-Provence)": "Le Cloître",
 "Le Château de Beaulieu (Pas-de-Calais)": "Meurin",
 "Le Mas de Pierre (Alpes-Maritimes)": "Pierre",
 "Château de Mercuès (Lot)": "Le Duèze",
 "Hôtel & Spa du Castellet (Var)": "Christophe Bacquié"
}

module.exports = data;
